### ISSUE TITLE
where can i download sdk 4.3

### ISSUE THREAD

**Issue by pc0808f** [MediaTek-Labs/linkit-7697-ble-smart-connection#1]
hi
this example is build by sdk 4.3.
so where can i found sdk 4.3?

**Comment by pablosun** [comment]
@pc0808f, sorry for getting this late - you should be able to download SDK version 4.3 in the MediaTek Labs page: https://docs.labs.mediatek.com/resource/mt7687-mt7697/en/downloads

**Comment by linus-gates** [comment]
Any chance you can reupload this file? @pc0808f @pablosun
